# SPDX-License-Identifier: AGPL-3.0-or-later
# infra-TAK — TAK Infrastructure Platform
# Copyright (C) 2026 Andreas Johansson (TAKWERX)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""TAK Simulator — registry module (v10.1.61, PLAN v10.1.61 §4.4).

Streams scripted, synthetic CoT into TAK Server on a channel the operator picks. The
engine lives in `simulator/` in this repo and runs in the `tak-simulator` container; this
file owns the console side: pre-flight, the `tak_simulation` channel, the lane identities
(one Authentik service account + one enrolled cert per lane — membership IS the channel
selector, §4.1), the compose stack, and the routes the page calls.

Imports NOTHING from app.py — every seam arrives through ctx. The only in-repo import is
`simulator.engine.scenario`, the single validator shared with the engine (§4.9).
"""
import base64
import glob
import http.client
import json
import os
import re
import secrets
import shutil
import socket
import ssl
import subprocess
import threading
import time
import urllib.error
import urllib.parse
import urllib.request

from . import register_module, job_log, job_state

SIM_KEY = 'simulator'
SIM_CONTAINER = 'tak-simulator'
SIM_INSTALL_DIR = os.path.expanduser('~/tak-simulator')
SIM_SOURCE_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'simulator')
SIM_CONTROL_PORT = 5090
SIM_DEFAULT_CHANNEL = 'tak_simulation'
SIM_LANE_USER_PREFIX = 'sim-lane-'
SIM_UPLOAD_PREFIX = 'upload-'
SIM_MAX_UPLOAD_BYTES = 1_000_000
SIM_SETTINGS_KEYS = ['simulator_enabled', 'simulator_control_token', 'simulator_lanes',
                     'simulator_default_channel', 'simulator_version']

_LANE_ID_RE = re.compile(r'[A-Za-z0-9][A-Za-z0-9_-]{0,15}')
_CHANNEL_RE = re.compile(r'tak_[A-Za-z0-9][A-Za-z0-9 ._-]{0,59}')
_NAME_RE = re.compile(r'[a-z0-9][a-z0-9-]{0,40}')
_SUBJ_VALUE_RE = re.compile(r'[A-Za-z0-9 ._-]{1,64}')


def _is_admin_group(channel):
    """tak_ROLE_ADMIN is TAK's adminGroup (CoreConfig `adminGroup="ROLE_ADMIN"`), not a
    channel: a lane enrolled there would be a TAK admin identity that reaches every
    channel. Rejected on every write path, not only hidden in the picker."""
    name = channel[4:] if channel.startswith('tak_') else channel
    return name.upper().startswith('ROLE_')

# Compose file infra-TAK writes into ~/tak-simulator (§4.2). Loopback-only control port,
# read-only root, no capabilities, the console user's uid so the 600 certs are readable,
# TAK reached at the host gateway (TAK core is always co-located with the console — §4.10).
# The scenarios mount is read-write since the director API (companion PLAN W9): /save
# writes `upload-*.json` layouts there — the engine never writes a preset name.
# W10: the service also joins the shared `infratak` network (external; created by the
# console, the same one TAK Portal <-> Authentik use) under the alias `tak-simulator`, so
# the CloudTAK api container can reach the control API by name. No new host port: the
# 127.0.0.1 publish stays for the console.
SIM_DOCKER_COMPOSE = '''\
# TAK Simulator — generated by infra-TAK v{version}; regenerated on every deploy/rebuild.
services:
  simulator:
    build:
      context: ./build
      dockerfile: Dockerfile
      args:
        SIM_VERSION: "{version}"
    image: infratak/tak-simulator:{version}
    container_name: tak-simulator
    user: "{uid}:{gid}"
    env_file: .env
    ports:
      - "127.0.0.1:{port}:{port}"
    volumes:
      - ./certs:/certs:ro
      - ./scenarios:/scenarios
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      default: {{}}
      {infratak_net}:
        aliases:
          - tak-simulator
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

networks:
  default: {{}}
  {infratak_net}:
    external: true
'''
SIM_INFRATAK_NETWORK = 'infratak'     # == app.py INFRATAK_DOCKER_NETWORK (fleet constant)


def _plog(msg):
    return job_log(SIM_KEY, msg)


def _audit(msg):
    """Journal line for every run/stop/channel change (C3 audit, §4.9) — `logger` is
    unprivileged, so it runs directly as the console user."""
    try:
        subprocess.run(['logger', '-t', 'tak-simulator', '--', msg], capture_output=True, timeout=5)
    except Exception:
        pass
    print(f'[tak-simulator] {msg}', flush=True)


def _scenario_mod():
    """The engine's validator, imported lazily from the sibling source tree."""
    try:
        from simulator.engine import scenario
        return scenario
    except ImportError:
        import importlib.util
        spec = importlib.util.spec_from_file_location(
            'sim_scenario', os.path.join(SIM_SOURCE_DIR, 'engine', 'scenario.py'))
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        return mod


# ── small clients ─────────────────────────────────────────────────────────────

def _ak(ctx, settings):
    """(base_url, headers) for Authentik API calls, or (None, None) when absent."""
    token = (ctx['_get_authentik_env_value'](settings, 'AUTHENTIK_BOOTSTRAP_TOKEN')
             or ctx['_get_authentik_env_value'](settings, 'AUTHENTIK_TOKEN'))
    if not token:
        return None, None
    base = ctx['_get_authentik_api_url'](settings) if ctx.get('_get_authentik_api_url') else 'http://127.0.0.1:9090'
    return base.rstrip('/') + '/api/v3', {'Authorization': f'Bearer {token}', 'Content-Type': 'application/json'}


def _ak_req(base, headers, path, method='GET', data=None, timeout=15):
    """Authentik request -> (status, json_or_None). Never raises on HTTP errors."""
    body = json.dumps(data).encode() if data is not None else None
    req = urllib.request.Request(f'{base}/{path.lstrip("/")}', data=body, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            raw = r.read()
            return r.status, (json.loads(raw.decode()) if raw.strip() else None)
    except urllib.error.HTTPError as e:
        try:
            raw = e.read().decode()[:300]
        except Exception:
            raw = ''
        return e.code, {'_error': raw}


def _ctl(settings, method, path, data=None, timeout=15):
    """Control-API request to the container -> (status, json). 0 = unreachable."""
    token = settings.get('simulator_control_token') or ''
    body = json.dumps(data).encode() if data is not None else None
    req = urllib.request.Request(f'http://127.0.0.1:{SIM_CONTROL_PORT}{path}', data=body, method=method,
                                 headers={'Authorization': f'Bearer {token}', 'Content-Type': 'application/json'})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            raw = r.read()
            return r.status, (json.loads(raw.decode()) if raw.strip() else {})
    except urllib.error.HTTPError as e:
        try:
            return e.code, json.loads(e.read().decode())
        except Exception:
            return e.code, {'error': f'HTTP {e.code}'}
    except (OSError, ValueError) as e:
        return 0, {'error': f'simulator engine unreachable: {str(e)[:120]}'}


def _tak_ssl_contexts(settings):
    """Verified TLS contexts for the loopback 8446 enrollment call, tried in order — never
    CERT_NONE. (1) The public CA store with TAK's public name as SNI/hostname
    (`takserver.<fqdn>` by default, or the operator's `takserver_domain` override; 8446 serves
    the Let's Encrypt certificate wherever Caddy issued one). (2) TAK's own CA bundle
    (`/opt/tak/certs/files/{ca,root-ca,ca-trusted}.pem` — public halves, world-readable) with
    chain verification only: a box without a public name serves the TAK-signed `takserver`
    cert whose SAN is not 127.0.0.1. Returns [(label, ctx, server_hostname)]."""
    out = []
    fqdn = (settings.get('fqdn') or '').strip()
    names = []
    custom = (settings.get('takserver_domain') or '').strip()
    if custom:
        names.append(custom if '.' in custom or not fqdn else f'{custom}.{fqdn}')
    if fqdn:
        names.append(f'takserver.{fqdn}')
        names.append(fqdn)
    for n in dict.fromkeys(names):
        out.append((f'public CA / SNI {n}', ssl.create_default_context(), n))
    cas = [f for f in ('/opt/tak/certs/files/ca.pem', '/opt/tak/certs/files/root-ca.pem',
                       '/opt/tak/certs/files/ca-trusted.pem') + tuple(sorted(glob.glob('/opt/tak/certs/files/truststore-*.pem')))
           if os.path.isfile(f) and os.access(f, os.R_OK)]
    if cas:
        c = ssl.create_default_context()
        c.check_hostname = False          # TAK server certs carry SAN=takserver; chain is still CERT_REQUIRED
        loaded = 0
        for f in cas:
            try:
                c.load_verify_locations(cafile=f)
                loaded += 1
            except (ssl.SSLError, OSError):
                pass
        if loaded:
            out.append(('TAK CA bundle', c, None))
    return out


def _tak_basic(user, password, path, method='GET', body=None, headers=None, timeout=20, settings=None):
    """Loopback 8446 call with HTTP basic auth (the enrollment surface), verified against
    the public CA store (SNI = FQDN) or TAK's own CA bundle — see _tak_ssl_contexts."""
    hdrs = {'Authorization': 'Basic ' + base64.b64encode(f'{user}:{password}'.encode()).decode()}
    hdrs.update(headers or {})
    last = None
    for label, sctx, sni in _tak_ssl_contexts(settings or {}):
        try:
            conn = http.client.HTTPSConnection('127.0.0.1', 8446, context=sctx, timeout=timeout)
            if sni:
                # SNI + hostname check against the public name while dialing loopback
                sock = socket.create_connection(('127.0.0.1', 8446), timeout=timeout)
                conn.sock = sctx.wrap_socket(sock, server_hostname=sni)
            conn.request(method, path, body=body, headers=hdrs)
            r = conn.getresponse()
            data = r.read()
            conn.close()
            if r.status >= 400:
                raise urllib.error.HTTPError(f'https://127.0.0.1:8446{path}', r.status, r.reason, r.headers, None)
            return r.status, data
        except ssl.SSLCertVerificationError as e:
            last = f'{label}: {str(e)[:100]}'
            continue
    raise OSError(f'8446 certificate could not be verified ({last or "no CA available"})')


def _tcp_open(host, port, timeout=4):
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except OSError:
        return False


# ── lanes: Authentik identity + enrollment ────────────────────────────────────

def _ensure_group(base, headers, name):
    """Return the pk of Authentik group `name`, creating it when absent."""
    st, res = _ak_req(base, headers, f'core/groups/?name={urllib.parse.quote(name)}')
    for g in (res or {}).get('results', []) if st == 200 else []:
        if g.get('name') == name:
            return g['pk'], False
    st, res = _ak_req(base, headers, 'core/groups/', 'POST', {'name': name, 'is_superuser': False})
    if st == 201 and res and res.get('pk'):
        return res['pk'], True
    raise RuntimeError(f'could not create Authentik group {name}: HTTP {st} {(res or {}).get("_error", "")[:120]}')


def _ensure_user(base, headers, username):
    """Return (pk, created) for the lane service account."""
    st, res = _ak_req(base, headers, f'core/users/?username={urllib.parse.quote(username)}')
    for u in (res or {}).get('results', []) if st == 200 else []:
        if u.get('username') == username:
            if u.get('path') != 'users' or not u.get('is_active', True):
                _ak_req(base, headers, f'core/users/{u["pk"]}/', 'PATCH', {'path': 'users', 'is_active': True})
            return u['pk'], False
    st, res = _ak_req(base, headers, 'core/users/', 'POST', {
        'username': username, 'name': f'TAK Simulator {username}', 'is_active': True,
        'type': 'service_account', 'path': 'users'})
    if st == 201 and res and res.get('pk'):
        return res['pk'], True
    raise RuntimeError(f'could not create Authentik user {username}: HTTP {st} {(res or {}).get("_error", "")[:120]}')


def _set_membership(base, headers, user_pk, group_pk):
    """Rewrite (not union) the lane user's groups to exactly [group_pk] — it is our user."""
    st, res = _ak_req(base, headers, f'core/users/{user_pk}/', 'PATCH', {'groups': [group_pk]})
    if st not in (200, 204):
        raise RuntimeError(f'could not set lane membership: HTTP {st} {(res or {}).get("_error", "")[:120]}')


def _set_password(base, headers, user_pk, password):
    st, _ = _ak_req(base, headers, f'core/users/{user_pk}/set_password/', 'POST', {'password': password})
    if st not in (200, 204):
        raise RuntimeError(f'could not set lane password: HTTP {st}')


def _enroll(username, password, cert_path, ca_path, version, plog, settings=None):
    """TAK certificate enrollment over 8446 (§4.10 item 2): tls/config -> CSR with the
    server's nameEntries -> signClient/v2 -> cert+key PEM (600) and the CA bundle.
    The password lives only in this call; the cert is the credential afterwards."""
    import xml.etree.ElementTree as ET
    cert_dir = os.path.dirname(cert_path)
    os.makedirs(cert_dir, mode=0o700, exist_ok=True)
    last = None
    for attempt in range(1, 7):
        try:
            st, raw = _tak_basic(username, password, '/Marti/api/tls/config', settings=settings)
            break
        except urllib.error.HTTPError as e:
            last = f'HTTP {e.code}'
        except OSError as e:
            last = str(e)[:120]
        plog(f'  enrollment: tls/config not ready for {username} ({last}); retry {attempt}/6 in 5s (LDAP outpost lag)')
        time.sleep(5)
    else:
        raise RuntimeError(f'enrollment: TAK did not accept {username} on 8446 ({last})')
    entries = {}
    for el in ET.fromstring(raw).iter():
        if el.tag.endswith('nameEntry') and el.get('name') and el.get('value'):
            if not _SUBJ_VALUE_RE.fullmatch(el.get('value')) or not re.fullmatch(r'[A-Z]{1,8}', el.get('name')):
                raise RuntimeError(f'enrollment: refusing odd nameEntry {el.get("name")!r}={el.get("value")!r}')
            entries[el.get('name')] = el.get('value')
    subj = f'/CN={username}' + ''.join(f'/{k}={v}' for k, v in entries.items())
    key_path = cert_path[:-4] + '.key'
    csr_path = cert_path[:-4] + '.csr'
    for p in (key_path, csr_path, cert_path):
        with open(p, 'w'):
            pass
        os.chmod(p, 0o600)
    r = subprocess.run(['openssl', 'req', '-new', '-newkey', 'rsa:2048', '-nodes', '-keyout', key_path,
                        '-out', csr_path, '-subj', subj], capture_output=True, text=True, timeout=60)
    if r.returncode != 0:
        raise RuntimeError(f'enrollment: openssl req failed: {(r.stderr or "")[-200:]}')
    with open(csr_path) as f:
        csr_b64 = ''.join(l.strip() for l in f if not l.startswith('-----'))
    q = urllib.parse.urlencode({'clientUid': username, 'version': version})
    st, raw = _tak_basic(username, password, f'/Marti/api/tls/signClient/v2?{q}', 'POST', csr_b64.encode(),
                         {'Content-Type': 'text/plain', 'Accept': 'application/json'}, timeout=40, settings=settings)
    res = json.loads(raw.decode())
    if not res.get('signedCert'):
        raise RuntimeError('enrollment: signClient/v2 returned no certificate')

    def _pem(b64):
        der = base64.b64decode(b64)
        return subprocess.run(['openssl', 'x509', '-inform', 'DER'], input=der, capture_output=True, timeout=10).stdout.decode()

    cert_pem = _pem(res['signedCert'])
    ca_pem = ''.join(_pem(res[k]) for k in sorted(res) if k.startswith('ca'))
    if 'BEGIN CERTIFICATE' not in cert_pem or 'BEGIN CERTIFICATE' not in ca_pem:
        raise RuntimeError('enrollment: could not decode the signed certificate or CA bundle')
    with open(key_path) as f:
        key_pem = f.read()
    with open(cert_path, 'w') as f:
        f.write(cert_pem + key_pem)
    os.chmod(cert_path, 0o600)
    with open(ca_path, 'w') as f:
        f.write(ca_pem)
    os.chmod(ca_path, 0o600)
    for p in (key_path, csr_path):
        try:
            os.remove(p)
        except OSError:
            pass
    plog(f'  ✓ enrolled {username}: subject {subj}, CA bundle {ca_pem.count("BEGIN CERTIFICATE")} cert(s)')


def _write_lanes_json(settings):
    """`~/tak-simulator/certs/lanes.json` = {lane_id: channel} for the engine (W9): it
    defaults `/live` and a lane-less `/run` to every enrolled lane on its recorded channel.
    Rewritten at deploy and on every lane change; 600 like the certs beside it."""
    d = os.path.join(SIM_INSTALL_DIR, 'certs')
    if not os.path.isdir(d):
        return
    m = {str(r['id']): r['channel'] for r in (settings.get('simulator_lanes') or [])
         if r.get('id') and r.get('channel')}
    path = os.path.join(d, 'lanes.json')
    tmp = f'{path}.tmp'
    with open(tmp, 'w') as f:
        json.dump(m, f)
    os.chmod(tmp, 0o600)
    os.replace(tmp, path)


def _lane_record(settings, lane_id):
    for rec in settings.get('simulator_lanes') or []:
        if str(rec.get('id')) == str(lane_id):
            return rec
    return None


def _ensure_lane(ctx, lane_id, channel, plog):
    """Ensure lane `lane_id` exists, is enrolled, and is a member of exactly `channel`
    (§4.1). Creates the service account + enrolls on first use; rewrites membership on a
    channel change. Returns the lane record. Persists settings."""
    if not _LANE_ID_RE.fullmatch(str(lane_id)):
        raise ValueError('bad lane id')
    if not _CHANNEL_RE.fullmatch(channel) or _is_admin_group(channel):
        raise ValueError('bad channel name')
    settings = ctx['load_settings']()
    base, headers = _ak(ctx, settings)
    if not base:
        raise RuntimeError('Authentik is not configured — the simulator needs Authentik LDAP')
    st, res = _ak_req(base, headers, f'core/groups/?name={urllib.parse.quote(channel)}')
    gpk = next((g['pk'] for g in (res or {}).get('results', []) if g.get('name') == channel), None) if st == 200 else None
    if not gpk:
        raise ValueError(f'channel {channel} does not exist in Authentik')
    username = f'{SIM_LANE_USER_PREFIX}{lane_id}'
    cert_dir = os.path.join(SIM_INSTALL_DIR, 'certs')
    cert_path = os.path.join(cert_dir, f'lane-{lane_id}.pem')
    ca_path = os.path.join(cert_dir, 'ca.pem')
    rec = _lane_record(settings, lane_id)
    upk, created = _ensure_user(base, headers, username)
    need_enroll = rec is None or not os.path.isfile(cert_path) or not os.path.isfile(ca_path)
    changed = rec is None or rec.get('channel') != channel or rec.get('ak_pk') != upk
    if changed:
        _set_membership(base, headers, upk, gpk)
        plog(f'  lane {lane_id}: {username} -> member of exactly [{channel}]')
    if need_enroll:
        password = secrets.token_urlsafe(24)
        _set_password(base, headers, upk, password)
        plog(f'  lane {lane_id}: enrolling {username} (CSR -> /Marti/api/tls/signClient/v2)')
        _enroll(username, password, cert_path, ca_path, ctx.get('VERSION', 'dev'), plog, settings=settings)
        del password
    settings = ctx['load_settings']()
    lanes = [r for r in (settings.get('simulator_lanes') or []) if str(r.get('id')) != str(lane_id)]
    rec = {'id': str(lane_id), 'user': username, 'ak_pk': upk, 'channel': channel,
           'cert': cert_path, 'enrolled_at': (rec or {}).get('enrolled_at') if not need_enroll else time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}
    lanes.append(rec)
    lanes.sort(key=lambda r: r['id'])
    settings['simulator_lanes'] = lanes
    ctx['save_settings'](settings)
    _write_lanes_json(settings)
    if need_enroll:
        _audit(f'lane {lane_id} ({username}) enrolled on {channel}')
    elif changed:
        _audit(f'lane {lane_id} ({username}) channel -> {channel}')
    return rec


# ── source tree / compose ─────────────────────────────────────────────────────

def _stage_build_dir(plog):
    """Copy Dockerfile + engine/ from the repo into ~/tak-simulator/build (the compose
    build context) so the image always matches the console version that wrote it."""
    build = os.path.join(SIM_INSTALL_DIR, 'build')
    if os.path.isdir(build):
        shutil.rmtree(build)
    os.makedirs(build, mode=0o755)
    shutil.copy2(os.path.join(SIM_SOURCE_DIR, 'Dockerfile'), os.path.join(build, 'Dockerfile'))
    shutil.copytree(os.path.join(SIM_SOURCE_DIR, 'engine'), os.path.join(build, 'engine'),
                    ignore=shutil.ignore_patterns('__pycache__', '*.pyc'))
    plog(f'  ✓ engine source staged into {build}')


def _copy_presets(plog):
    dst = os.path.join(SIM_INSTALL_DIR, 'scenarios')
    os.makedirs(dst, mode=0o755, exist_ok=True)
    n = 0
    for name in sorted(os.listdir(os.path.join(SIM_SOURCE_DIR, 'scenarios'))):
        if name.endswith('.json') and _NAME_RE.fullmatch(name[:-5]) and not name.startswith(SIM_UPLOAD_PREFIX):
            shutil.copy2(os.path.join(SIM_SOURCE_DIR, 'scenarios', name), os.path.join(dst, name))
            os.chmod(os.path.join(dst, name), 0o644)
            n += 1
    plog(f'  ✓ {n} preset scenario(s) installed (operator uploads kept)')


def _video_base(ctx, settings):
    """rtsp://<host>:8554 when MediaMTX or TAK Video Restreamer is installed, else ''."""
    modules = ctx['detect_modules']()
    if not (modules.get('mediamtx', {}).get('installed') or modules.get('tak_video_restreamer', {}).get('installed')):
        return ''
    host = (settings.get('fqdn') or '').strip() or (settings.get('server_ip') or '').strip()
    return f'rtsp://{host}:8554' if host else ''


def _write_env(ctx, settings, token, version, plog):
    lines = [
        f'SIM_CONTROL_TOKEN={token}',
        f'SIM_CONTROL_BIND=0.0.0.0:{SIM_CONTROL_PORT}',
        'SIM_TAK_HOST=host.docker.internal',
        'SIM_TAK_PORT=8089',
        'SIM_TAK_API_PORT=8443',
        'SIM_CERT_DIR=/certs',
        'SIM_CA_FILE=/certs/ca.pem',
        'SIM_SCENARIO_DIR=/scenarios',
        f'SIM_VIDEO_RTSP_BASE={_video_base(ctx, settings)}',
        f'SIM_DEFAULT_CHANNEL={SIM_DEFAULT_CHANNEL}',
        f'SIM_VERSION={version}',
    ]
    path = os.path.join(SIM_INSTALL_DIR, '.env')
    with open(path, 'w'):
        pass
    os.chmod(path, 0o600)
    with open(path, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    plog('  ✓ .env written (600)')


def _write_compose(version, plog):
    path = os.path.join(SIM_INSTALL_DIR, 'docker-compose.yml')
    with open(path, 'w') as f:
        f.write(SIM_DOCKER_COMPOSE.format(version=version, uid=os.getuid(), gid=os.getgid(),
                                          port=SIM_CONTROL_PORT, infratak_net=SIM_INFRATAK_NETWORK))
    plog('  ✓ docker-compose.yml written (control API 127.0.0.1 only + infratak network, read-only root, cap_drop ALL)')


def _ensure_network(ctx, plog):
    """The compose file declares `infratak` external — create it (idempotent) first (W10)."""
    fn = ctx.get('_ensure_infratak_docker_network')
    if fn:
        fn()
        plog(f'  ✓ docker network {SIM_INFRATAK_NETWORK} present')


def _link_cloudtak(ctx, plog):
    """Rewrite CloudTAK's override from current settings and recreate its api container
    when needed (W10): with `simulator_enabled` set, the api joins `infratak` and gets
    TAKSIM_ENGINE_URL/TOKEN; with it cleared, both go away. No-op without CloudTAK."""
    fn = ctx.get('_cloudtak_refresh_override')
    if not fn:
        return False, 'override refresh seam not available'
    try:
        return fn(plog)
    except Exception as e:      # never fail the simulator job on the CloudTAK side
        return False, f'CloudTAK link skipped: {str(e)[:200]}'


def _compose_argv(ctx, *action):
    return ['docker', 'compose', '--project-directory', SIM_INSTALL_DIR] + list(action)


def _wait_healthy(settings, plog, timeout=90):
    deadline = time.time() + timeout
    while time.time() < deadline:
        st, res = _ctl(settings, 'GET', '/health', timeout=5)
        if st == 200 and (res or {}).get('ok'):
            return res
        time.sleep(3)
    return None


# ── lifecycle ─────────────────────────────────────────────────────────────────

def detect(ctx):
    settings = ctx['load_settings']()
    enabled = bool(settings.get('simulator_enabled'))
    running = False
    try:
        r = ctx['probe_run'](['docker', 'inspect', '--format', '{{.State.Running}}', SIM_CONTAINER],
                             capture_output=True, text=True, timeout=3)
        running = (r.stdout or '').strip() == 'true'
    except Exception:
        pass
    if running and not enabled:
        s = ctx['load_settings']()
        s['simulator_enabled'] = True
        ctx['save_settings'](s)
        enabled = True
    return {'installed': enabled, 'running': running}


def get_version_info(ctx):
    """The engine ships inside the console: 'update available' = the image was built by
    an older console version than the one running now (rebuild re-stages the source)."""
    settings = ctx['load_settings']()
    have = (settings.get('simulator_version') or '').strip()
    want = ctx.get('VERSION', 'dev')
    return {'version': have, 'latest': want, 'update_available': bool(have) and have != want}


def deploy(ctx, job, params):
    plog = _plog
    try:
        settings = ctx['load_settings']()
        version = ctx.get('VERSION', 'dev')
        plog('━━━ Step 1/7: Pre-flight ━━━')
        modules = ctx['detect_modules']()
        problems = []
        if not modules.get('takserver', {}).get('installed'):
            problems.append('TAK Server is not installed on this box')
        base, headers = _ak(ctx, settings)
        if not base:
            problems.append('Authentik is not installed (the simulator needs Authentik LDAP for its lane identities)')
        if not _tcp_open('127.0.0.1', 8089):
            problems.append('TAK Server streaming port 127.0.0.1:8089 is not reachable')
        if not _tcp_open('127.0.0.1', 8446):
            problems.append('TAK Server enrollment port 127.0.0.1:8446 is not reachable')
        for p in problems:
            plog(f'  ✗ {p}')
        if problems:
            raise RuntimeError('pre-flight failed — fix the items above and deploy again')
        plog('  ✓ TAK Server installed, 8089 + 8446 reachable, Authentik API available')
        rc, dv = ctx['_docker_probe']()
        if rc != 0:
            plog('  Docker not found — installing...')
            if not ctx['_install_docker_engine'](plog):
                raise RuntimeError('Docker install failed — see log above')
            plog('  ✓ Docker installed')
        else:
            plog(f'  ✓ Docker present: {dv}')

        plog('')
        plog(f'━━━ Step 2/7: Channel {SIM_DEFAULT_CHANNEL} ━━━')
        gpk, created = _ensure_group(base, headers, SIM_DEFAULT_CHANNEL)
        plog(f'  ✓ {"created" if created else "exists"}: {SIM_DEFAULT_CHANNEL} (TAK channel "simulation")')

        plog('')
        plog('━━━ Step 3/7: Lane identity + enrollment ━━━')
        os.makedirs(SIM_INSTALL_DIR, mode=0o700, exist_ok=True)
        os.chmod(SIM_INSTALL_DIR, 0o755)
        os.makedirs(os.path.join(SIM_INSTALL_DIR, 'certs'), mode=0o700, exist_ok=True)
        rec = _ensure_lane(ctx, '1', SIM_DEFAULT_CHANNEL, plog)
        plog(f'  ✓ lane 1 = {rec["user"]} on {rec["channel"]}, cert {rec["cert"]}')

        plog('')
        plog('━━━ Step 4/7: Writing configuration ━━━')
        settings = ctx['load_settings']()
        token = settings.get('simulator_control_token') or secrets.token_urlsafe(32)
        settings['simulator_control_token'] = token
        ctx['save_settings'](settings)
        _stage_build_dir(plog)
        _copy_presets(plog)
        _write_env(ctx, settings, token, version, plog)
        _write_compose(version, plog)

        plog('')
        plog('━━━ Step 5/7: Building & starting container ━━━')
        _ensure_network(ctx, plog)
        plog('  ⏳ First build pulls the pinned python:3.12-slim base — allow 1–3 min...')
        r = ctx['_broker_compose'](SIM_INSTALL_DIR, 'up -d --build', timeout=600)
        if r.returncode != 0:
            raise RuntimeError(f'docker compose up --build failed:\n{(r.stderr or r.stdout)[-600:]}')
        plog('  ✓ container built and started')
        health = _wait_healthy(settings, plog)
        if not health:
            raise RuntimeError('engine did not answer on 127.0.0.1:5090 within 90 s — see docker logs tak-simulator')
        plog(f'  ✓ engine healthy (version {health.get("version")})')

        plog('')
        plog('━━━ Step 6/7: Registering module ━━━')
        s = ctx['load_settings']()
        s['simulator_enabled'] = True
        s['simulator_default_channel'] = SIM_DEFAULT_CHANNEL
        s['simulator_version'] = version
        ctx['save_settings'](s)
        _audit(f'deployed v{version}; lane 1 on {SIM_DEFAULT_CHANNEL}')

        plog('')
        plog('━━━ Step 7/7: CloudTAK link ━━━')
        changed, msg = _link_cloudtak(ctx, plog)
        plog(f'  {"✓" if changed else "·"} {msg}')
        if changed:
            plog('  The CloudTAK TAK Simulator panel can be installed from this page (CloudTAK rebuild, 5–10 min).')
        plog('')
        plog('✓ TAK Simulator deployed.')
        plog(f'  Viewers: add users to the "{SIM_DEFAULT_CHANNEL[4:]}" channel in TAK Portal and toggle it on in ATAK.')
        plog('  Nothing is sent until you press Start on the Simulator page.')
        job.update({'running': False, 'complete': True, 'error': False})
    except Exception as exc:
        plog(f'ERROR: {exc}')
        job.update({'running': False, 'complete': False, 'error': True})


def uninstall(ctx, job, params):
    """Stop (deletes go out), compose down, remove lane users, remove the install dir,
    clear settings. The tak_simulation channel stays unless the operator ticks the box."""
    steps = []
    settings = ctx['load_settings']()
    st, _ = _ctl(settings, 'POST', '/stop', {}, timeout=40)
    if st == 200:
        steps.append('Running scenario stopped (delete events sent)')
    if os.path.isfile(os.path.join(SIM_INSTALL_DIR, 'docker-compose.yml')):
        ctx['_broker_compose'](SIM_INSTALL_DIR, 'down --rmi local', timeout=120)
        steps.append('Container and image removed')
    base, headers = _ak(ctx, settings)
    if base:
        n = 0
        for rec in settings.get('simulator_lanes') or []:
            if rec.get('ak_pk') and str(rec.get('user', '')).startswith(SIM_LANE_USER_PREFIX):
                st, _ = _ak_req(base, headers, f'core/users/{rec["ak_pk"]}/', 'DELETE')
                n += 1 if st in (200, 204, 404) else 0
        steps.append(f'{n} lane identit{"y" if n == 1 else "ies"} removed from Authentik')
        if (params or {}).get('remove_channel'):
            st, res = _ak_req(base, headers, f'core/groups/?name={urllib.parse.quote(SIM_DEFAULT_CHANNEL)}')
            for g in (res or {}).get('results', []) if st == 200 else []:
                if g.get('name') == SIM_DEFAULT_CHANNEL:
                    _ak_req(base, headers, f'core/groups/{g["pk"]}/', 'DELETE')
                    steps.append(f'Channel {SIM_DEFAULT_CHANNEL} removed')
        else:
            steps.append(f'Channel {SIM_DEFAULT_CHANNEL} kept (viewer memberships are theirs)')
    if os.path.isdir(SIM_INSTALL_DIR):
        shutil.rmtree(SIM_INSTALL_DIR, ignore_errors=True)
        steps.append('Install directory removed (certs, scenarios, uploads)')
    s = ctx['load_settings']()
    for k in SIM_SETTINGS_KEYS:
        s.pop(k, None)
    ctx['save_settings'](s)
    changed, msg = _link_cloudtak(ctx, lambda m: print(f'[tak-simulator] {m}', flush=True))
    if changed:
        steps.append('CloudTAK api container recreated without the engine link (network + token removed)')
    _audit('uninstalled')
    return {'success': True, 'steps': steps}


# ── rebuild (engine update) — own slot, never the deploy job slot ─────────────
_rebuild_status = {'running': False, 'complete': False, 'error': False, 'log': []}


def _run_rebuild(ctx):
    log = []

    def plog(msg):
        log.append(msg)
        _rebuild_status['log'] = list(log)
    try:
        settings = ctx['load_settings']()
        version = ctx.get('VERSION', 'dev')
        st, _ = _ctl(settings, 'POST', '/stop', {}, timeout=40)
        plog('━━━ Step 1/3: Re-staging engine source ━━━')
        _stage_build_dir(plog)
        _copy_presets(plog)
        _write_env(ctx, settings, settings.get('simulator_control_token') or '', version, plog)
        _write_compose(version, plog)
        _write_lanes_json(settings)          # W9: pre-director installs have no lanes.json yet
        plog('━━━ Step 2/3: Rebuilding image ━━━')
        _ensure_network(ctx, plog)
        r = ctx['_broker_compose'](SIM_INSTALL_DIR, 'up -d --build', timeout=600)
        plog((r.stdout + r.stderr).strip()[-600:] or '(no output)')
        if r.returncode != 0:
            raise RuntimeError('docker compose build failed')
        if not _wait_healthy(settings, plog):
            raise RuntimeError('engine did not come back healthy')
        plog('━━━ Step 3/3: Saving version + CloudTAK link ━━━')
        s = ctx['load_settings']()
        s['simulator_version'] = version
        ctx['save_settings'](s)
        changed, msg = _link_cloudtak(ctx, plog)      # W10: an upgraded install links CloudTAK too
        plog(f'  {"✓" if changed else "·"} {msg}')
        plog(f'✓ TAK Simulator engine rebuilt at v{version}')
        _rebuild_status.update({'running': False, 'complete': True, 'error': False})
    except Exception as exc:
        plog(f'ERROR: {exc}')
        _rebuild_status.update({'running': False, 'complete': False, 'error': str(exc)})


# ── registration ──────────────────────────────────────────────────────────────

def register(ctx):
    from flask import request, jsonify

    def _lanes_view():
        return [{k: r.get(k) for k in ('id', 'user', 'channel', 'enrolled_at')} for r in (ctx['load_settings']().get('simulator_lanes') or [])]

    def channels_view():
        settings = ctx['load_settings']()
        base, headers = _ak(ctx, settings)
        if not base:
            return jsonify({'channels': [], 'error': 'Authentik not configured'}), 503
        st, res = _ak_req(base, headers, 'core/groups/?search=tak_&page_size=200&ordering=name')
        if st != 200:
            return jsonify({'channels': [], 'error': f'Authentik HTTP {st}'}), 502
        out = []
        for g in (res or {}).get('results', []):
            n = g.get('name') or ''
            if n.startswith('tak_') and not _is_admin_group(n) and _CHANNEL_RE.fullmatch(n):
                out.append({'name': n, 'channel': n[4:], 'is_simulation': n == SIM_DEFAULT_CHANNEL})
        return jsonify({'channels': out, 'default': SIM_DEFAULT_CHANNEL})

    def scenarios_view():
        sc = _scenario_mod()
        d = os.path.join(SIM_INSTALL_DIR, 'scenarios')
        out = []
        try:
            names = sorted(os.listdir(d))
        except OSError:
            names = []
        for name in names:
            if not name.endswith('.json') or not _NAME_RE.fullmatch(name[:-5]):
                continue
            entry = {'name': name[:-5], 'upload': name.startswith(SIM_UPLOAD_PREFIX)}
            try:
                with open(os.path.join(d, name), 'rb') as f:
                    doc = sc.validate_bytes(f.read(), name[:-5])
                entry.update(sc.summarize(doc))
                entry['valid'] = True
            except sc.ScenarioError as e:
                entry.update({'valid': False, 'errors': e.errors[:10]})
            except OSError as e:
                entry.update({'valid': False, 'errors': [str(e)[:120]]})
            out.append(entry)
        return jsonify({'scenarios': out})

    def upload_view():
        sc = _scenario_mod()
        if (request.content_length or 0) > SIM_MAX_UPLOAD_BYTES + 4096:
            return jsonify({'error': 'file larger than 1 MB'}), 413
        f = request.files.get('file')
        raw = f.read(SIM_MAX_UPLOAD_BYTES + 1) if f else request.get_data(cache=False)[:SIM_MAX_UPLOAD_BYTES + 1]
        if not raw:
            return jsonify({'error': 'no scenario file in the request'}), 400
        try:
            doc = sc.validate_bytes(raw, 'upload')
        except sc.ScenarioError as e:
            return jsonify({'error': 'scenario rejected', 'errors': e.errors[:20]}), 400
        name = f'{SIM_UPLOAD_PREFIX}{secrets.token_hex(4)}'
        doc['name'] = name
        d = os.path.join(SIM_INSTALL_DIR, 'scenarios')
        os.makedirs(d, exist_ok=True)
        with open(os.path.join(d, f'{name}.json'), 'w') as fh:
            json.dump(doc, fh, indent=1)
        _audit(f'scenario uploaded as {name} ({doc["title"]!r}, {len(doc["entities"])} entities, {len(doc["events"])} events)')
        return jsonify({'saved': name, 'summary': sc.summarize(doc)})

    def delete_scenario_view(name):
        if not _NAME_RE.fullmatch(name or '') or not name.startswith(SIM_UPLOAD_PREFIX):
            return jsonify({'error': 'only uploaded scenarios can be deleted'}), 400
        p = os.path.join(SIM_INSTALL_DIR, 'scenarios', f'{name}.json')
        if not os.path.isfile(p):
            return jsonify({'error': 'not found'}), 404
        os.remove(p)
        _audit(f'scenario {name} deleted')
        return jsonify({'deleted': name})

    def lanes_view():
        if request.method == 'GET':
            return jsonify({'lanes': _lanes_view(), 'default': SIM_DEFAULT_CHANNEL})
        data = request.get_json(silent=True) or {}
        lane_id = str(data.get('lane') or '').strip()
        channel = str(data.get('channel') or '').strip()
        if not _LANE_ID_RE.fullmatch(lane_id) or not _CHANNEL_RE.fullmatch(channel) or _is_admin_group(channel):
            return jsonify({'error': 'lane id or channel name has an invalid format'}), 400
        try:
            rec = _ensure_lane(ctx, lane_id, channel, lambda m: print(f'[tak-simulator] {m}', flush=True))
        except ValueError as e:
            return jsonify({'error': str(e)}), 400
        except Exception as e:
            return jsonify({'error': str(e)[:300]}), 502
        return jsonify({'lane': {k: rec.get(k) for k in ('id', 'user', 'channel', 'enrolled_at')}})

    def run_view():
        data = request.get_json(silent=True) or {}
        lanes_in = data.get('lanes') or {}
        if not isinstance(lanes_in, dict) or not lanes_in:
            return jsonify({'error': 'lanes must map lane id -> channel'}), 400
        for lid, ch in lanes_in.items():
            if not _LANE_ID_RE.fullmatch(str(lid)) or not isinstance(ch, str) or not _CHANNEL_RE.fullmatch(ch) or _is_admin_group(ch):
                return jsonify({'error': f'bad lane assignment {lid!r}'}), 400
        real = sorted({ch for ch in lanes_in.values() if ch != SIM_DEFAULT_CHANNEL})
        typed = ''
        if real:
            typed = str(data.get('confirm_exercise') or '').strip()
            if typed != ', '.join(real):
                return jsonify({'error': 'a real channel needs a typed confirmation', 'confirm_required': ', '.join(real)}), 400
        plog = lambda m: print(f'[tak-simulator] {m}', flush=True)
        try:
            for lid, ch in lanes_in.items():
                _ensure_lane(ctx, str(lid), ch, plog)
        except ValueError as e:
            return jsonify({'error': str(e)}), 400
        except Exception as e:
            return jsonify({'error': str(e)[:300]}), 502
        payload = {
            'scenario': data.get('scenario'),
            'center': data.get('center'),
            'tempo': data.get('tempo', 1),
            'loop': data.get('loop'),
            'exercise': bool(real),
            'confirm_exercise': typed,      # the engine re-checks it (W9 double gate)
            'default_channel': SIM_DEFAULT_CHANNEL,
            'lanes': {str(lid): {'channel': ch, 'exercise': ch != SIM_DEFAULT_CHANNEL} for lid, ch in lanes_in.items()},
            'params': data.get('params') or {},
        }
        settings = ctx['load_settings']()
        st, res = _ctl(settings, 'POST', '/run', payload, timeout=90)
        if st == 200:
            _audit(f'run started: {res.get("scenario")} lanes={res.get("lanes")} tempo={payload["tempo"]}'
                   f'{" EXERCISE on real channel(s) " + ", ".join(real) if real else ""}')
        return jsonify(res), (200 if st == 200 else (st or 503))

    def _passthrough(path, verb):
        def view():
            settings = ctx['load_settings']()
            st, res = _ctl(settings, 'POST', path, {}, timeout=60)
            if st == 200:
                _audit(f'{verb} -> {res.get("state")}')
            return jsonify(res), (200 if st == 200 else (st or 503))
        view.__name__ = f'simulator_{verb}_view'
        return view

    def status_view():
        settings = ctx['load_settings']()
        st, res = _ctl(settings, 'GET', '/status', timeout=8)
        out = {'engine': res if st == 200 else None, 'engine_error': None if st == 200 else res.get('error'),
               'lanes': _lanes_view(), 'default': SIM_DEFAULT_CHANNEL,
               'version': get_version_info(ctx)}
        return jsonify(out)

    def logs_view():
        try:
            r = subprocess.run(ctx['_sudo_wrap'](['docker', 'logs', '--tail', '200', SIM_CONTAINER]),
                               capture_output=True, text=True, timeout=15)
            raw = (r.stdout + r.stderr).splitlines()
            return jsonify({'lines': raw[-200:]})
        except Exception as e:
            return jsonify({'lines': [], 'error': str(e)})

    def rebuild_view():
        if _rebuild_status.get('running'):
            return jsonify({'started': False, 'error': 'Rebuild already in progress'})
        _rebuild_status.update({'running': True, 'complete': False, 'error': False, 'log': []})
        threading.Thread(target=_run_rebuild, args=(ctx,), daemon=True).start()
        return jsonify({'started': True})

    def rebuild_status_view():
        return jsonify(_rebuild_status)

    register_module({
        'key': SIM_KEY,
        'name': 'TAK Simulator',
        'description': 'Scripted exercises, demos and load tests streamed into a TAK channel you pick',
        'icon': '\U0001F3AF',   # 🎯 as escape — Edit-tool surrogate trap
        'route': '/simulator',
        'template': 'simulator.html',
        'priority': 14,
        'conflicts': [],
        'detect': detect,
        'deploy': deploy,
        'uninstall': uninstall,
        'control_map': {
            'start':   lambda c: _compose_argv(c, 'up', '-d'),
            'stop':    lambda c: _compose_argv(c, 'stop'),
            'restart': lambda c: _compose_argv(c, 'restart'),
        },
        'extra_routes': [
            {'url': '/api/simulator/channels', 'methods': ['GET'], 'endpoint': 'simulator_channels', 'view': channels_view},
            {'url': '/api/simulator/scenarios', 'methods': ['GET'], 'endpoint': 'simulator_scenarios', 'view': scenarios_view},
            {'url': '/api/simulator/scenarios/upload', 'methods': ['POST'], 'endpoint': 'simulator_scenario_upload', 'view': upload_view},
            {'url': '/api/simulator/scenarios/<name>', 'methods': ['DELETE'], 'endpoint': 'simulator_scenario_delete', 'view': delete_scenario_view},
            {'url': '/api/simulator/lanes', 'methods': ['GET', 'POST'], 'endpoint': 'simulator_lanes', 'view': lanes_view},
            {'url': '/api/simulator/run', 'methods': ['POST'], 'endpoint': 'simulator_run', 'view': run_view},
            {'url': '/api/simulator/pause', 'methods': ['POST'], 'endpoint': 'simulator_pause', 'view': _passthrough('/pause', 'pause')},
            {'url': '/api/simulator/resume', 'methods': ['POST'], 'endpoint': 'simulator_resume', 'view': _passthrough('/resume', 'resume')},
            {'url': '/api/simulator/stop', 'methods': ['POST'], 'endpoint': 'simulator_stop', 'view': _passthrough('/stop', 'stop')},
            {'url': '/api/simulator/status', 'methods': ['GET'], 'endpoint': 'simulator_status', 'view': status_view},
            {'url': '/api/simulator/logs', 'methods': ['GET'], 'endpoint': 'simulator_logs', 'view': logs_view},
            {'url': '/api/simulator/rebuild', 'methods': ['POST'], 'endpoint': 'simulator_rebuild', 'view': rebuild_view},
            {'url': '/api/simulator/rebuild-status', 'methods': ['GET'], 'endpoint': 'simulator_rebuild_status', 'view': rebuild_status_view},
        ],
        'ports': [],                  # control API is 127.0.0.1:5090 only — no firewall rule (guide §9.3)
        'service_units': [],
        'settings_keys': SIM_SETTINGS_KEYS,
    })
