"""TAK Video Restreamer — second registry-resident module (v10.1.24).

Moved from app.py (SOLID Wave 3, PLAN v10.1.24 §4-W2), behavior-preserving at
the URL/response-shape level except the two deliberate contract fixes:
full-console uninstall now removes TVR (registry uninstall is the ONE copy),
and /control follows the 10.1.22 canonical contract (unknown verb -> 400).

This is the migration that proves the registry's Docker axes: compose lifecycle
in a DYNAMIC install dir (~/tak-video-restreamer, or /root/… on a box flipped
from root — TVR is NOT auto-re-homed, its compose has absolute binds), a Caddy
subdomain, a self-update path (git SHA based — upstream ships off main with no
releases), and the MediaMTX port conflict (same stream ports).

This file imports NOTHING from app.py — every seam (settings, privileged file
IO, sudo wrap, broker compose/git, docker install, Authentik proxy app hooks)
arrives through the ctx dict handed to register(ctx).
"""
import os
import json
import subprocess
import threading

from . import register_module, job_log, job_state

TVR_REPO = "https://github.com/raytheonbbn/tak-video-restreamer.git"
TVR_INSTALL_DIR = os.path.expanduser("~/tak-video-restreamer")

# infra-TAK overrides two addresses from the upstream mediaMTX.yml:
#   apiAddress  0.0.0.0:8889 → 127.0.0.1:8889  (API must never be public)
#   hlsAddress  :8888        → 127.0.0.1:8888   (HLS reached via Caddy /hls-proxy/)
TVR_MEDIAMTX_YML = '''\
# TAK Video Restreamer - MediaMTX configuration (generated by infra-TAK)
readTimeout: 10s
writeTimeout: 10s
writeQueueSize: 512
udpMaxPayloadSize: 1452

authMethod: internal
authInternalUsers:
  - user: any
    ips: []
    permissions:
      - action: publish
      - action: read
      - action: playback
  - user: any
    ips: ['127.0.0.1', '::1']
    permissions:
      - action: api
      - action: metrics
      - action: pprof

# v0.9.42: API bound to loopback — must never be publicly exposed
api: yes
apiAddress: 127.0.0.1:8889

rtsp: yes
rtspAddress: 0.0.0.0:8554
rtspTransports: [tcp]
rtspEncryption: optional
rtspsAddress: 0.0.0.0:8555
rtspServerCert: /opt/app/certs/server.crt
rtspServerKey: /opt/app/certs/server.key

rtmp: yes
rtmpAddress: 0.0.0.0:1935

# v0.9.42: HLS bound to loopback — Caddy proxies /hls-proxy/* to this port
hls: yes
hlsAddress: 127.0.0.1:8888
hlsEncryption: no
hlsTrustedProxies: ['127.0.0.1']
hlsVariant: fmp4
hlsSegmentCount: 3
hlsSegmentDuration: 500ms
hlsPartDuration: 200ms
hlsSegmentMaxSize: 50M
hlsMuxerCloseAfter: 60s
hlsAlwaysRemux: yes

webrtc: no
webrtcAddress: :9898

srt: yes
srtAddress: 0.0.0.0:8890

pathDefaults:
  source: publisher
  record: no
  recordPath: /opt/app/streams/%path/%Y-%m-%d_%H-%M-%S
  overridePublisher: yes
  srtPublishPassphrase: ""
  srtReadPassphrase: ""

paths:
  ~^tak-.*$:
    source: publisher
    record: no

  ~^drone.*$:
    source: publisher
    record: no

  ~^uas.*$:
    source: publisher
    record: no

  ~^(.+)_hls$:
    runOnDemand: ffmpeg -rtsp_transport tcp -analyzeduration 2000000 -probesize 2000000 -i rtsp://localhost:8554/$G1 -c:v libx264 -preset ultrafast -tune zerolatency -profile:v baseline -level 3.1 -pix_fmt yuv420p -b:v 2M -maxrate 2.5M -bufsize 5M -g 30 -keyint_min 30 -sc_threshold 0 -c:a aac -b:a 128k -ar 48000 -ac 2 -err_detect ignore_err -fflags +genpts+discardcorrupt -f rtsp -rtsp_transport tcp rtsp://localhost:8554/$MTX_PATH
    runOnDemandStartTimeout: 10s
    runOnDemandCloseAfter: 10s
    runOnDemandRestart: yes

  ~^.*$:
    source: publisher
'''

# infra-TAK docker-compose for TAK Video Restreamer.
# Key bindings vs upstream:
#   3000  → 127.0.0.1 only  (web UI, Caddy proxies)
#   8888  → 127.0.0.1 only  (native HLS, Caddy /hls-proxy/)
#   8554/8555/8890/1935 → 0.0.0.0 (streaming clients access directly)
#   8889  NOT published     (MediaMTX API stays inside container)
TVR_DOCKER_COMPOSE = '''\
version: '3.8'
services:
  media:
    build:
      context: {tvr_dir}
      dockerfile: Dockerfile
    container_name: tak-video-restreamer
    ports:
      - "127.0.0.1:3100:3000"
      - "0.0.0.0:8554:8554"
      - "0.0.0.0:8555:8555"
      - "0.0.0.0:1935:1935"
      - "0.0.0.0:8890:8890/udp"
      - "127.0.0.1:8888:8888"
    volumes:
      - {tvr_dir}/mediaMTX.yml:/opt/app/mediamtx.yml:ro
      - {tvr_dir}/data/streams:/opt/app/streams
      - {tvr_dir}/data/logs:/opt/app/logs
      - {tvr_dir}/data/hls:/opt/app/hls
      - {tvr_dir}/data:/opt/app/data
      - {tvr_dir}/data/certs:/opt/app/certs
    environment:
      - PORT=3000
      - MEDIAMTX_API_URL=http://localhost:8889
      - MEDIAMTX_RTSP_URL=rtsp://127.0.0.1:8554
      - MEDIAMTX_HLS_URL=http://127.0.0.1:8888
      - PYTHONUNBUFFERED=1
      - STREAMS_DIR=/opt/app/streams
      - DATA_DIR=/opt/app/data
      - ACTIVE_CERTS_DIR=/opt/app/certs
      - LOGS_DIR=/opt/app/logs
      - HLS_OUTPUT_DIR=/opt/app/hls
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD={admin_pass}
      - SECRET_KEY={secret_key}
      - CORS_ORIGINS={cors_origins}
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
'''


def _plog(msg):
    return job_log('tvr', msg)


_tvr_release_cache = {'sha': None, 'ts': 0}


def get_latest_commit_sha(use_cache=True):
    """Latest commit SHA (full) on main for raytheonbbn/tak-video-restreamer.
    The repo ships off main with no releases, so the commit SHA is the only
    version signal. Cached 4h — like CloudTAK/Authentik — because this lookup
    runs on every dashboard poll AND every TVR page load; unauthenticated GitHub
    is 60 req/hr/IP, and a 403 would otherwise silently blank the update badge.
    Returns stale cache on failure rather than None so a rate-limit doesn't hide
    a known-available update. Pass use_cache=False to force a fresh check."""
    import time as _time
    if use_cache and _tvr_release_cache['sha'] and (_time.time() - _tvr_release_cache['ts'] < 14400):
        return _tvr_release_cache['sha']
    try:
        import urllib.request as _ur
        req = _ur.Request('https://api.github.com/repos/raytheonbbn/tak-video-restreamer/commits/main',
                          headers={'Accept': 'application/vnd.github+json', 'User-Agent': 'infra-TAK'})
        with _ur.urlopen(req, timeout=10) as resp:
            sha = (json.loads(resp.read().decode()).get('sha') or '').strip() or None
            if sha:
                _tvr_release_cache['sha'] = sha
                _tvr_release_cache['ts'] = _time.time()
            return sha
    except Exception as e:
        print(f"version-info: tvr latest-commit check failed (non-fatal): {e}", flush=True)
        return _tvr_release_cache.get('sha') or None


def tvr_dir(ctx):
    """Resolve the real TAK Video Restreamer install dir. Fresh born-non-root installs live at
    ~/tak-video-restreamer; a box FLIPPED from root keeps it at /root/tak-video-restreamer (TVR is
    NOT auto-re-homed — its compose has ABSOLUTE /root binds + a bind-mounted data dir, like WebODM).
    Returns whichever holds a compose (broker-checked, since takwerx can't stat /root), else ~."""
    home = TVR_INSTALL_DIR
    if os.path.exists(os.path.join(home, 'docker-compose.yml')):
        return home
    try:
        if subprocess.run(ctx['_sudo_wrap'](['test', '-f', '/root/tak-video-restreamer/docker-compose.yml']),
                          capture_output=True, timeout=10).returncode == 0:
            return '/root/tak-video-restreamer'
    except Exception:
        pass
    return home


def _compose(ctx, dirpath, action, timeout=120):
    """Run `docker compose <action>` in the TVR dir via the broker — root reaches /root on a
    flipped box; --project-directory replaces the old bash-cd (denied by the rulebook)."""
    return ctx['_broker_compose'](dirpath, action, timeout=timeout)


def _compose_argv(ctx, *action):
    """Argv form of _compose for the registry control_view (which sudo-wraps and
    runs it itself) — same --project-directory semantics."""
    return ['docker', 'compose', '--project-directory', tvr_dir(ctx)] + list(action)


def get_version_info(ctx):
    """Return {version, update_available, latest} for TAK Video Restreamer (git SHA based).
    Compares FULL local vs remote SHAs — git's --short length is adaptive (7+ as the repo
    grows) so the old short-vs-[:7] compare could mismatch; display values stay 7 chars."""
    info = {'version': '', 'update_available': False, 'latest': None}
    dirpath = tvr_dir(ctx)
    local_full = ''
    try:
        r = ctx['_module_git'](dirpath, 'rev-parse', 'HEAD', timeout=8)
        if r.returncode == 0:
            local_full = r.stdout.strip()
            info['version'] = local_full[:7]
    except Exception as e:
        print(f"version-info: tvr local SHA lookup failed (non-fatal): {e}", flush=True)
    latest_full = get_latest_commit_sha()
    if latest_full:
        info['latest'] = latest_full[:7]
        if local_full and local_full != latest_full:
            info['update_available'] = True
    return info


def detect(ctx):
    """Settings flag + `docker inspect` liveness — unchanged logic, moved from
    the detect_modules() inline block (incl. the enabled-flag self-heal)."""
    settings = ctx['load_settings']()
    enabled = settings.get('tak_video_restreamer_enabled', False)
    running = False
    if enabled:
        try:
            r = ctx['probe_run'](
                ['docker', 'inspect', '--format', '{{.State.Running}}', 'tak-video-restreamer'],
                capture_output=True, text=True, timeout=3)
            running = (r.stdout or '').strip() == 'true'
        except Exception:
            pass
    else:
        # Self-heal: container is running but flag got cleared
        try:
            r = ctx['probe_run'](
                ['docker', 'inspect', '--format', '{{.State.Running}}', 'tak-video-restreamer'],
                capture_output=True, text=True, timeout=3)
            if (r.stdout or '').strip() == 'true':
                s = ctx['load_settings']()
                s['tak_video_restreamer_enabled'] = True
                ctx['save_settings'](s)
                enabled = True
                running = True
        except Exception:
            pass
    return {'installed': bool(enabled), 'running': running}


def deploy(ctx, job, params):
    import secrets as _sec
    plog = _plog
    tvr_dir_ = TVR_INSTALL_DIR
    compose_path = os.path.join(tvr_dir_, 'docker-compose.yml')
    mtx_yml_path = os.path.join(tvr_dir_, 'mediaMTX.yml')
    try:
        settings = ctx['load_settings']()
        # Guard: refuse if standalone mediamtx is installed (same stream ports)
        modules = ctx['detect_modules']()
        if modules.get('mediamtx', {}).get('installed'):
            plog('✗ Cannot deploy: standalone MediaMTX is installed and uses the same ports (8554/8555/8888/8890).')
            plog('  Uninstall MediaMTX first, then deploy TAK Video Restreamer.')
            job.update({'running': False, 'error': True})
            return

        # Step 1: Ensure Docker is present
        plog('━━━ Step 1/6: Checking Docker ━━━')
        _rc, _dv = ctx['_docker_probe']()
        if _rc != 0:
            plog('  Docker not found — installing...')
            if not ctx['_install_docker_engine'](plog):
                raise RuntimeError('Docker install failed — see log above')
            plog('✓ Docker installed')
        else:
            plog(f'✓ Docker present: {_dv}')

        # Step 2: Clone or update repo
        plog('')
        plog('━━━ Step 2/6: Cloning Repository ━━━')
        if os.path.isdir(os.path.join(tvr_dir_, '.git')):
            plog(f'  Repo already cloned at {tvr_dir_} — pulling latest...')
            # Discard the console-written overlay (compose/mediaMTX.yml/arm64 Dockerfile) so the
            # pull can't abort on "local changes" — Step 3 regenerates all of it anyway.
            subprocess.run(['git', '-C', tvr_dir_, 'checkout', '--', '.'],
                           capture_output=True, text=True, timeout=30)
            r = subprocess.run(['git', '-C', tvr_dir_, 'pull', '--ff-only'],
                               capture_output=True, text=True, timeout=60)
            plog(f'  git pull: {r.stdout.strip() or r.stderr.strip()}')
        else:
            os.makedirs(tvr_dir_, exist_ok=True)
            plog(f'  Cloning {TVR_REPO} → {tvr_dir_}')
            r = subprocess.run(['git', 'clone', '--depth=1', TVR_REPO, tvr_dir_],
                               capture_output=True, text=True, timeout=120)
            if r.returncode != 0:
                raise RuntimeError(f'git clone failed: {r.stderr[:300]}')
            plog('✓ Repository cloned')

        # Record the commit SHA for audit
        sha_r = subprocess.run(['git', '-C', tvr_dir_, 'rev-parse', '--short', 'HEAD'],
                               capture_output=True, text=True)
        commit_sha = sha_r.stdout.strip() or 'unknown'
        plog(f'  Commit SHA: {commit_sha}')

        # v10.0.1 (arm64): the upstream TVR Dockerfile hardcodes the MediaMTX
        # linux_amd64 release tarball, so on aarch64 the bundled mediamtx binary is
        # wrong-arch and crash-loops with "exec format error" at runtime (the
        # python:3.11-slim base is multi-arch, so the image itself builds fine).
        # Rewrite the embedded download to linux_arm64 (bluenviron's arm64 asset is
        # named `_linux_arm64`, NOT `_linux_arm64v8` — matches infra-TAK's own
        # aarch64→arm64 map for the standalone MediaMTX module) before the build.
        # No-op on amd64 — the upstream Dockerfile is used unchanged.
        if ctx['_host_arch']() == 'arm64':
            _tvr_dockerfile = os.path.join(tvr_dir_, 'Dockerfile')
            try:
                with open(_tvr_dockerfile) as _df:
                    _dfc = _df.read()
                if '_linux_amd64' in _dfc and 'mediamtx_' in _dfc:
                    with open(_tvr_dockerfile, 'w') as _df:
                        _df.write(_dfc.replace('_linux_amd64', '_linux_arm64'))
                    plog('  ✓ arm64: patched TVR Dockerfile MediaMTX binary linux_amd64 → linux_arm64')
                else:
                    plog('  ⚠ arm64: TVR Dockerfile MediaMTX amd64 pattern not found — bundled mediamtx may be wrong-arch')
            except Exception as _de:
                plog(f'  ⚠ arm64: could not patch TVR Dockerfile for arm64 (mediamtx may fail): {_de}')

        # Step 3: Write infra-TAK compose + mediaMTX.yml
        plog('')
        plog('━━━ Step 3/6: Writing Configuration ━━━')
        for sub in ['data', 'data/streams', 'data/logs', 'data/hls', 'data/certs']:
            os.makedirs(os.path.join(tvr_dir_, sub), exist_ok=True)

        admin_pass = settings.get('tak_video_restreamer_admin_password') or _sec.token_hex(16)
        secret_key = settings.get('tak_video_restreamer_secret_key') or _sec.token_hex(32)
        fqdn = settings.get('fqdn', '').strip()
        cors_origins = f'https://{fqdn}' if fqdn else 'http://localhost:3100'

        compose_content = TVR_DOCKER_COMPOSE.format(
            tvr_dir=tvr_dir_,
            admin_pass=admin_pass,
            secret_key=secret_key,
            cors_origins=cors_origins,
        )
        with open(compose_path, 'w') as f:
            f.write(compose_content)
        plog('✓ docker-compose.yml written')

        with open(mtx_yml_path, 'w') as f:
            f.write(TVR_MEDIAMTX_YML)
        plog('✓ mediaMTX.yml written (HLS + API bound to loopback)')

        # Step 4: Build and start container
        # First-build can take 5–10 min on a cold host — warn operator
        plog('')
        plog('━━━ Step 4/6: Building & Starting Container ━━━')
        plog('  ⏳ First build downloads + compiles dependencies — allow 5–10 min...')
        r = subprocess.run(ctx['_sudo_wrap'](['docker', 'compose', '-f', compose_path, 'up', '-d', '--build']),
                           capture_output=True, text=True, timeout=900, cwd=tvr_dir_)
        if r.returncode != 0:
            raise RuntimeError(f'docker compose up --build failed:\n{r.stderr[-500:]}')
        plog('✓ Container built and started')

        # Step 5: UFW rules
        plog('')
        plog('━━━ Step 5/6: Configuring Firewall ━━━')
        if ctx['os_type']() == 'rhel':
            # No ufw on RHEL — a bare argv `ufw` call raises FileNotFoundError and
            # aborts the deploy. Stream ports reach the box via the cloud SG; the web
            # UI / HLS are blocked from direct access by firewalld default-deny / SG
            # (Caddy is the entry point). Proper firewalld allow/deny = firewall-parity track.
            plog('  (RHEL: ufw absent — stream ports via SG; web UI/HLS Caddy-only via firewalld default-deny/SG)')
        else:
            for port_proto in ['8554/tcp', '8555/tcp', '1935/tcp', '8890/udp']:
                subprocess.run(ctx['_sudo_wrap'](['ufw', 'allow', port_proto]), capture_output=True)
                plog(f'  ✓ ufw allow {port_proto}')
            # Block direct access to web UI and HLS — Caddy is the only entry point
            # TVR web UI is on host port 3100 (not 3000 — that's TAK Portal)
            for port_proto in ['3100/tcp', '8888/tcp']:
                subprocess.run(ctx['_sudo_wrap'](['ufw', 'deny', port_proto]), capture_output=True)
                plog(f'  ✓ ufw deny {port_proto} (Caddy-only)')

        # Step 6: Save settings + regenerate Caddyfile
        plog('')
        plog('━━━ Step 6/6: Registering Module ━━━')
        s = ctx['load_settings']()
        s['tak_video_restreamer_enabled'] = True
        s['tak_video_restreamer_admin_password'] = admin_pass
        s['tak_video_restreamer_secret_key'] = secret_key
        s['tak_video_restreamer_commit_sha'] = commit_sha
        ctx['save_settings'](s)
        ctx['generate_caddyfile'](s)
        # v10.1.50: ctx['_caddy_reload'] never raises and never hangs. The try/except that
        # used to be here could not protect the Authentik block below it from a reload that
        # blocked past its timeout — Caddy's grace period defaults to eternal, so that was
        # not hypothetical (see _caddy_reload_checked in app.py).
        if ctx['_caddy_reload'](plog):
            plog('✓ Caddy reloaded')

        # Optional: register Authentik proxy provider
        ak_token = (ctx['_get_authentik_env_value'](s, 'AUTHENTIK_TOKEN') or
                    ctx['_get_authentik_env_value'](s, 'AUTHENTIK_BOOTSTRAP_TOKEN'))
        if fqdn and ak_token:
            plog('  Configuring Authentik for TAK Video Restreamer...')
            ctx['_ensure_authentik_tvr_app'](fqdn, ak_token, plog=plog, settings=s)
        else:
            plog('  Authentik not configured — skipping proxy provider setup.')

        plog('')
        plog('✓ TAK Video Restreamer deployed successfully.')
        plog(f'  Web UI: https://{fqdn}/  (admin / {admin_pass})' if fqdn else
             f'  Web UI: http://localhost:3100/  (admin / {admin_pass})')
        plog('  RTSP:   rtsp://<host>:8554/<stream>')
        plog('  RTSPS:  rtsps://<host>:8555/<stream>')
        plog('  SRT:    srt://<host>:8890?streamid=publish:<stream>')
        plog('  RTMP:   rtmp://<host>:1935/<stream>')
        job.update({'running': False, 'complete': True, 'error': False})
    except Exception as exc:
        plog(f'ERROR: {exc}')
        job.update({'running': False, 'complete': False, 'error': True})


def uninstall(ctx, job, params):
    """Compose down + Caddy/Authentik dereg. Deliberately leaves the install dir
    (stream configs/recordings under data/) — matches pre-registry behavior.
    Password gate is the generic registry preamble (PLAN v10.1.24 §4-W2)."""
    steps = []
    dirpath = tvr_dir(ctx)
    if subprocess.run(ctx['_sudo_wrap'](['test', '-f', os.path.join(dirpath, 'docker-compose.yml')]),
                      capture_output=True, timeout=10).returncode == 0:
        _compose(ctx, dirpath, 'down', timeout=60)
        steps.append('Containers stopped and removed')
    s = ctx['load_settings']()
    s['tak_video_restreamer_enabled'] = False
    ctx['save_settings'](s)
    ctx['generate_caddyfile'](s)
    ctx['_caddy_reload']()
    steps.append('Caddy subdomain removed')
    ctx['_deregister_authentik_proxy_app'](s, 'tak-video-restreamer', 'TAK Video Restreamer Proxy')
    steps.append('Authentik proxy app deregistered')
    return {'success': True, 'steps': steps}


# Self-update slot — deliberately slot-local (NOT the registry deploy job slot):
# update and deploy must never share a lock/log (PLAN v10.1.24 §4-W2).
_update_status = {'running': False, 'complete': False, 'error': False, 'log': []}


def _run_update(ctx):
    import secrets as _sec
    global _update_status
    log = []
    def plog(msg):
        log.append(msg)
        _update_status['log'] = list(log)
    try:
        dirpath = tvr_dir(ctx)   # ~/tak-video-restreamer OR (flipped box) /root/tak-video-restreamer
        plog('━━━ Step 1/4: Pulling latest source ━━━')
        # infra-TAK OWNS docker-compose.yml + mediaMTX.yml (rewritten from templates at deploy)
        # and patches the Dockerfile on arm64, so the clone is permanently dirty on tracked
        # files — a plain pull aborts with "local changes would be overwritten by merge" the
        # moment upstream touches them. Discard the console-written overlay, pull, then
        # regenerate it in Step 2 (nothing user-authored lives in tracked files).
        r = ctx['_module_git'](dirpath, 'checkout', '--', '.', timeout=60)
        if r.returncode == 0:
            r = ctx['_module_git'](dirpath, 'pull', '--ff-only', timeout=120)
        plog((r.stdout + r.stderr).strip() or '(no output)')
        if r.returncode != 0:
            raise RuntimeError(f'git pull failed: {r.stderr[:300]}')
        r2 = ctx['_module_git'](dirpath, 'rev-parse', '--short', 'HEAD', timeout=8)
        new_sha = r2.stdout.strip()
        plog(f'✓ Now at commit {new_sha}')

        plog('')
        plog('━━━ Step 2/4: Re-applying infra-TAK configuration ━━━')
        s = ctx['load_settings']()
        admin_pass = s.get('tak_video_restreamer_admin_password') or _sec.token_hex(16)
        secret_key = s.get('tak_video_restreamer_secret_key') or _sec.token_hex(32)
        if (s.get('tak_video_restreamer_admin_password') != admin_pass
                or s.get('tak_video_restreamer_secret_key') != secret_key):
            s['tak_video_restreamer_admin_password'] = admin_pass
            s['tak_video_restreamer_secret_key'] = secret_key
            ctx['save_settings'](s)
        fqdn = (s.get('fqdn') or '').strip()
        cors_origins = f'https://{fqdn}' if fqdn else 'http://localhost:3100'
        ctx['_write_priv'](os.path.join(dirpath, 'docker-compose.yml'),
                           TVR_DOCKER_COMPOSE.format(tvr_dir=dirpath, admin_pass=admin_pass,
                                                     secret_key=secret_key, cors_origins=cors_origins))
        ctx['_write_priv'](os.path.join(dirpath, 'mediaMTX.yml'), TVR_MEDIAMTX_YML)
        plog('✓ docker-compose.yml + mediaMTX.yml regenerated (loopback binds, admin password preserved)')
        if ctx['_host_arch']() == 'arm64':
            _tvr_dockerfile = os.path.join(dirpath, 'Dockerfile')
            try:
                _dfc = ctx['_read_priv'](_tvr_dockerfile)
                if '_linux_amd64' in _dfc and 'mediamtx_' in _dfc:
                    ctx['_write_priv'](_tvr_dockerfile, _dfc.replace('_linux_amd64', '_linux_arm64'))
                    plog('✓ arm64: re-patched Dockerfile MediaMTX binary linux_amd64 → linux_arm64')
                else:
                    plog('⚠ arm64: Dockerfile MediaMTX amd64 pattern not found — bundled mediamtx may be wrong-arch')
            except Exception as _de:
                plog(f'⚠ arm64: could not re-patch Dockerfile (mediamtx may fail): {_de}')

        plog('')
        plog('━━━ Step 3/4: Rebuilding Docker image ━━━')
        r = _compose(ctx, dirpath, 'up -d --build', timeout=600)
        plog((r.stdout + r.stderr).strip()[-600:] or '(no output)')
        if r.returncode != 0:
            raise RuntimeError(f'docker compose build failed: {r.stderr[:300]}')

        plog('')
        plog('━━━ Step 4/4: Saving new SHA ━━━')
        s = ctx['load_settings']()
        s['tak_video_restreamer_commit_sha'] = new_sha
        ctx['save_settings'](s)
        plog(f'✓ TAK Video Restreamer updated to {new_sha}')
        _update_status.update({'running': False, 'complete': True, 'error': False})
    except Exception as exc:
        plog(f'ERROR: {exc}')
        _update_status.update({'running': False, 'complete': False, 'error': str(exc)})


def register(ctx):
    from flask import request, jsonify

    def deploy_status_view():
        # Pre-registry /deploy-status shape ({running,complete,error,log}) —
        # NOT the registry /log 'entries' shape; tvr.html polls this URL.
        job = job_state('tvr')
        return jsonify({'running': job['running'], 'complete': job['complete'],
                        'error': job['error'], 'log': list(job['log'])})

    def logs_view():
        try:
            r = subprocess.run(ctx['_sudo_wrap'](['docker', 'logs', '--tail', '200', 'tak-video-restreamer']),
                               capture_output=True, text=True, timeout=15)
            raw = (r.stdout + r.stderr).splitlines()
            return jsonify({'lines': raw[-200:]})
        except Exception as e:
            return jsonify({'lines': [], 'error': str(e)})

    def set_password_view():
        data = request.get_json(silent=True) or {}
        new_password = (data.get('password') or '').strip()
        if len(new_password) < 6:
            return jsonify({'error': 'Password must be at least 6 characters'}), 400
        # v10.1.4 (WS4): the password is written verbatim into a root-run compose file —
        # reject newlines/control chars outright (a newline in `.*` re.sub survives and
        # injects an extra compose line; control chars have no business in a password).
        if any(ord(ch) < 32 or ord(ch) == 127 for ch in new_password):
            return jsonify({'error': 'Password must not contain newlines or control characters'}), 400
        s = ctx['load_settings']()
        s['tak_video_restreamer_admin_password'] = new_password
        ctx['save_settings'](s)
        # Rewrite docker-compose.yml with the new password and restart (no rebuild)
        dirpath = tvr_dir(ctx)
        compose_path = os.path.join(dirpath, 'docker-compose.yml')
        if subprocess.run(ctx['_sudo_wrap'](['test', '-f', compose_path]), capture_output=True, timeout=10).returncode == 0:
            try:
                content = ctx['_read_priv'](compose_path)   # v10.0.5 non-root: broker (root-owned on flipped box)
                import re as _re
                # Callable replacement — a plain f-string replacement lets re.sub interpret
                # backslash escapes in the password (`\1`, `\g<0>` corrupt the write).
                content = _re.sub(r'(- ADMIN_PASSWORD=).*',
                                  lambda m: m.group(1) + new_password, content)
                ctx['_write_priv'](compose_path, content)
                _compose(ctx, dirpath, 'up -d', timeout=60)
            except Exception as e:
                return jsonify({'error': str(e)}), 500
        return jsonify({'success': True})

    def update_view():
        global _update_status
        if _update_status.get('running'):
            return jsonify({'started': False, 'error': 'Update already in progress'})
        _update_status = {'running': True, 'complete': False, 'error': False, 'log': []}
        threading.Thread(target=_run_update, args=(ctx,), daemon=True).start()
        return jsonify({'started': True})

    def update_status_view():
        return jsonify(_update_status)

    register_module({
        # identity / UI
        'key': 'tvr',
        'api_base': '/api/tak-video-restreamer',   # frozen pre-registry URLs
        'name': 'TAK Video Restreamer',
        'description': 'Flask + MediaMTX restreamer — RTSP, RTSPS, SRT, HLS, KLV',
        'icon': '\U0001F3A5',  # 🎥 as escape — Edit-tool surrogate trap ([[apppy-emoji-surrogate-escape-trap]])
        'icon_url': 'https://raw.githubusercontent.com/raytheonbbn/tak-video-restreamer/main/web/static/tak_video_restreamer_logo.png',
        'route': '/tak-video-restreamer',
        'template': 'tvr.html',
        'priority': 13,
        'conflicts': ['mediamtx'],   # same stream ports (8554/8555/8888/8890)
        # state probes + lifecycle
        'detect': detect,
        'deploy': deploy,
        'uninstall': uninstall,
        'control_map': {
            # callables (v10.1.24): compose dir is runtime state — ~ on fresh
            # installs, /root/tak-video-restreamer on a box flipped from root
            'start':   lambda c: _compose_argv(c, 'up', '-d'),
            'stop':    lambda c: _compose_argv(c, 'stop'),
            'restart': lambda c: _compose_argv(c, 'restart'),
        },
        # bespoke routes stay bespoke, visible, and enumerable
        'extra_routes': [
            {'url': '/api/tak-video-restreamer/deploy-status', 'methods': ['GET'],
             'endpoint': 'tvr_deploy_status', 'view': deploy_status_view},
            {'url': '/api/tak-video-restreamer/logs', 'methods': ['GET'],
             'endpoint': 'tvr_logs', 'view': logs_view},
            {'url': '/api/tak-video-restreamer/set-password', 'methods': ['POST'],
             'endpoint': 'tvr_set_password', 'view': set_password_view},
            {'url': '/api/tak-video-restreamer/update', 'methods': ['POST'],
             'endpoint': 'tvr_update', 'view': update_view},
            {'url': '/api/tak-video-restreamer/update-status', 'methods': ['GET'],
             'endpoint': 'tvr_update_status', 'view': update_status_view},
        ],
        # facts (data for later waves — recorded so 10.1.25+ don't re-survey)
        'ports': ['8554/tcp', '8555/tcp', '1935/tcp', '8890/udp'],  # streaming, direct; 3100/8888 loopback+Caddy-only
        'service_units': [],           # docker compose only — no systemd unit
        'settings_keys': ['tak_video_restreamer_enabled', 'tak_video_restreamer_admin_password',
                          'tak_video_restreamer_secret_key', 'tak_video_restreamer_commit_sha'],
    })
